/**
 * API 模块统一导出（与 console 对齐）
 */
export * from './modules/common'
export * from './modules/setting'
export * from './modules/domain'
export * from './modules/channel'
export * from './modules/order'
export * from './modules/provider'
export * from './modules/subscription'
export * from './modules/agent'
export * from './modules/ai-link'
export * from './modules/auth'
export * from './modules/template-style'
export * from './modules/user'
export * from './modules/group'
export * from './modules/navigation'
export * from './modules/payment'
export * from './modules/spaces'
export * from './modules/system-log'
export * from './modules/record'
export * from './modules/banner'
export * from './modules/platform-settings'
export * from './modules/providers'
export * from './modules/libraries'
export * from './modules/feedback'
export * from './modules/message'
export * from './modules/permissions'
export * from './modules/chunk-setting'
export * from './modules/upload'
export * from './modules/chunks'
export * from './modules/conversation'
export * from './modules/license'
export * from './modules/prompt'
export * from './modules/saas'
export * from './modules/wecom'
export * from './modules/dingtalk'
export * from './modules/wps'
export * from './modules/agents'
export * from './modules/department'
export * from './modules/enterprise'
export * from './modules/rag-pipeline'
export * from './modules/rag-strategy'
export * from './modules/graph-templates'
export * from './modules/files'

export { default as service } from './config'
export { get, post, put, del, patch } from './config'
