package session

const (
	SESSION_USER_ID          = "SESSION_USER_ID"
	SESSION_USER_NICKNAME    = "SESSION_USER_NICKNAME"
	SESSION_USER_ROLE        = "SESSION_USER_ROLE"
	SESSION_USER_GROUP_ID    = "SESSION_USER_GROUP_ID"
	ENV_EID                  = "ENV_EID"
	SESSION_AGENT_MODEL      = "SESSION_AGENT_MODEL"
	SESSION_AGENT_ID         = "SESSION_AGENT_ID"
	SESSION_AGENT            = "SESSION_AGENT"
	SESSION_CONVERSATION_ID  = "SESSION_CONVERSATION_ID"
	SESSION_CONVERSATION     = "SESSION_CONVERSATION"
	SESSION_SAAS_USER        = "SESSION_SAAS_USER"
	SESSION_REQUEST_PROTOCOL = "SESSION_REQUEST_PROTOCOL"
	SESSION_REQUEST_DOMAIN   = "SESSION_REQUEST_DOMAIN"
	SESSION_VISITOR_ID       = "SESSION_VISITOR_ID"
)
