/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const OverflowTooltip: typeof import('@km/shared-components-react')['OverflowTooltip']
}
